name: 发布清单

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  BuildAndPublish:
    runs-on: ubuntu-latest
    steps:
      - name: 检出分支
        uses: actions/checkout@v3

      - name: 执行生成清单
        run: |
          chmod +x getManifest.sh
          ./getManifest.sh url.txt dist/freecdn-internal/

      - name: 检查清单
        run: |
          cat dist/freecdn-internal/freecdn-manifest.txt

      - name: 提交到发布分支
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with: 
          branch: release
          folder: dist
          clean: true

  Deploy:
    runs-on: ubuntu-latest
    needs: BuildAndPublish
    steps:
      - name: 检出分支
        uses: actions/checkout@v3
        with:
          ref: release

      - name: 发布到服务器上
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_GITHUB_SSH_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/.*, /node_modules/"